version: '3'

networks:
  docker-server:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
      - mysql
    networks:
      - docker-server

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./www:/var/www/html
      - ./mysql:/var/lib/mysql
    command: mysqld --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: libra
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - docker-server

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php
    restart: unless-stopped
    volumes: 
      - ./www:/var/www/html
      - /home/whleucka/Music:/music
    ports:
      - "9000:9000"
    networks:
      - docker-server

        # cron:
        #   build:
        #     context: .
        #     dockerfile: cron/Dockerfile
        #   container_name: cron
        #   restart: unless-stopped
        #   volumes:
        #     - ./www:/var/www/html
        #     - /home/whleucka/Music:/music
        #   networks:
        #     - docker-server
